mybatis:
  mapper-locations: classpath:com/woniu/mapper/*.xml
  #别名
  type-aliases-package: com.woniu.entity
  configuration:
    #数据库下划线转实体类驼峰命名法
    map-underscore-to-camel-case: true
spring:
  application:
    name: HospitalSystem
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://192.172.0.5/HOSPITAL?useUincode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: 192.172.0.5
    port: 6379
#sql语句日志输出
logging:
  level:
    org:
      springframework:
        web: debug
    com:
      woniu:
        mapper: debug

pagehelper:
  reasonable: true

