mybatis:
  mapper-locations: classpath:com/woniu/mapper/*.xml
  #别名
  type-aliases-package: com.woniu.entity
  configuration:
    #数据库下划线转实体类驼峰命名法
    map-underscore-to-camel-case: true
server:
  port: 8080
spring:
  application:
    name: HospitalSystem
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/hos?useUincode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: 192.172.0.5
    port: 6379
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: utf-8
    username: swttty@qq.com
    password: qwlydbhnnltxdgbe
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#sql语句日志输出
logging:
  level:
    org:
      springframework:
        web: debug
    com:
      woniu:
        mapper: debug

pagehelper:
  reasonable: true

